site_name: 'Documentation du Bot Discord Zone01'
site_author: 'Makcimerrr'
copyright: 'Copyright © 2024 Makcimerrr'
nav:
  - Accueil: index.md
  - Guide d'utilisation:
      - Introduction: guide/introduction.md
      - Commandes: guide/commandes.md
  - Référence API:
      - Cogs:
          - Gestion CDI: cogs/gestion_cdi.md
          - Gestion Help: cogs/gestion_help.md
          - Gestion Jobs: cogs/gestion_jobs.md
          - Gestion Ping: cogs/gestion_ping.md
          - Gestion Event: cogs/event_cog.md
  - Utilitaires:
      - Utils:
          - Fetch CDI: utils/cdi_fetcher.md
          - Fetch Jobs: utils/job_fetcher.md
          - Scheduler: utils/scheduler.md
          - Config Loader: utils/config_loader.md
  - Configuration: config.md
  - Contribuer: contributor.md
theme:
  name: material
palette:
  primary: green
  accent: light green
background: white
font:
  text: 'Roboto'
  code: 'Roboto Mono'
  headline: 'Roboto'
  logo: 'Roboto'
favicon: 'https://cdn.discordapp.com/attachments/831271000000000000/831271000000000000/zone01.png'
repo_url: "https://github.com/makcimerrr/bot-discord-zone01"
repo_name: "bot-discord-zone01"
edit_uri: "edit/main/docs/"
site_url: "https://makcimerrr.github.io/bot-discord-zone01/"
